yarnPath: ".yarn/releases/yarn-berry.cjs"
nodeLinker: "pnp"
pnpMode: "loose"
packageExtensions:
  "eslint@7.5.0":
    peerDependencies:
      "eslint-config-react-app": "*"
  "@testing-library/dom@>=7.21.4":
    peerDependencies:
      "@testing-library/user-event": "^12.1.10"
  "@typescript-eslint/eslint-plugin@^4.0.0":
    peerDependencies:
      "eslint-config-react-app": "^6.0.0"
  "@typescript-eslint/parser@^4.0.0":
    peerDependencies:
      "eslint-config-react-app": "^6.0.0"
  "babel-eslint@^10.0.0":
    peerDependencies:
      "eslint-config-react-app": "^6.0.0"
  "eslint-plugin-flowtype@^5.2.0":
    peerDependencies:
      "eslint-config-react-app": "^6.0.0"
  "eslint-plugin-import@^2.22.0":
    peerDependencies:
      "eslint-config-react-app": "^6.0.0"
  "eslint-plugin-jsx-a11y@^6.3.1":
    peerDependencies:
      "eslint-config-react-app": "^6.0.0"
  "eslint-plugin-react@^7.20.3":
    peerDependencies:
      "eslint-config-react-app": "^6.0.0"
  "eslint-plugin-react-hooks@^4.0.8":
    peerDependencies:
      "eslint-config-react-app": "^6.0.0"
  "react@*":
      dependencies:
        prop-types: "*"
